language: bash
services: docker

env:
  - WORKSPACE=~/workspace

install:
  - git clone https://github.com/thyrlian/MUNS "$WORKSPACE"

before_script:
  - cd "$WORKSPACE"

script:
  - docker build -t muns .

after_script:
  - docker images
