version: '2'

services:
  ruby:
    build: ./rich-ruby
    env_file: env/ruby.env
    command: /init/ruby.sh
    volumes:
      - $UNICORN_SOCKET
      - ./volumes/init:/init
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
      - /data/configdb

  nginx:
    image: nginx
    env_file: env/nginx.env
    command: /init/nginx.sh
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - ruby:ro
    depends_on:
      - ruby
